server:
  port: 80

yc:
  isopen: true
  starter:
    name: yc
    content: hello
  datasource:
    driverclass: com.mysql.cj.jdbc.Driver
    jdbcurl: "jdbc:mysql://localhost:3306/db_testbank?serverTimezone=GMT%2B8"
    user: root
    password: a

logging:
  level:
    root: error
    com.yc: debug
    org.springframework: error
  file:
    path: ./logs
#    name: yc.log