server:
  port: 80
  servlet:
    context-path: /mybank
    session:
      timeout: 6000

logging:
  level:
    root: error
    com.yc: debug
    org.springframework: error
  file:
    path: ./logs

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_testbank?serverTimezone=GMT%2B8
    username: root
    password: a
swagger:
  enable: true